# Generated by Django 5.2.4 on 2025-08-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vManufacturer', models.CharField(max_length=50)),
                ('vModel', models.CharField(max_length=50)),
                ('fleetID', models.CharField(max_length=50)),
                ('ownerInfo', models.TextField(max_length=200)),
                ('regStatus', models.CharField(max_length=10)),
            ],
        ),
    ]
