# Generated by Django 5.2.4 on 2025-08-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
        ('vehicleFleet', '0002_vehicle_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='diagnostics_codes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='engine_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='odometer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='telemetry',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicleFleet.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='telemetry',
            unique_together={('vehicle', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['vehicle', 'created_at'], name='telemetry_a_vehicle_ba25a0_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'created_at'], name='telemetry_a_alert_t_c32db3_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['vehicle', 'timestamp'], name='telemetry_t_vehicle_efa0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['speed'], name='telemetry_t_speed_c405db_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['fuel_level'], name='telemetry_t_fuel_le_824380_idx'),
        ),
    ]
